from core.exception import CoreException

class PrivateMethodCalledError(CoreException):
    pass
